### ISSUE TITLE
[FR] Auto-save

### ISSUE THREAD

**Issue by oparoz** [ari/jobsworth#393]
Maybe other people would find it useful if draft tasks or comments could be automatically saved at regular interval.

Use case:
You're hosting JW on a shared environment.
You're writing a task description and doing some research at the same time. It takes a bit longer than planned.
During that time, another user makes a modification to his environment
Apache restart.
Now comes the time to save the task, but unfortunately, you've been logged out and you've lost everything.

**Comment by ari** [comment]
An old feature request that realistically isn't going to get any love since it doesn't impact me. We've moved away from mod_ruby sort of hosting, so the server should be robust and upgrades more seamless.
