### ISSUE TITLE
Remove customer_id attribute from user

### ISSUE THREAD

**Issue by vshete** [ari/jobsworth#502]
Since Customers are linked to companies and each company has users there is no reason for a customer_id to be present for a user. There would not be any customer_id present for a user which is not available with his company.  There is no direct connection between a user and a customer. customer_id for a user is only adding to confusion.

When a user is edited the Value entered in the Company field on the web page gets assigned to project_id of the user at back end. The company field auto complete should show company names if at all the admin is allowed to assign a user to a company other than his own.

At present when the user is created he is by default assigned to a company same as the admin. The admin cannot later change the company because at the back end the project_id would change instead of company_id when the user is edited.

This would require quite a lot of work around. For example, at present if you try to edit a customer, you could associate users to that customer by creating new users with company (customer_id at back end) as customer

@ari Should we remove the customer_id. Also should the admin be allowed to see all the companies in the database. Should he be allowed to create users for companies other than his.

**Comment by ari** [comment]
I don't see the benefit in this task, so closing.
