### ISSUE TITLE
Small issues on Timeline

### ISSUE THREAD

**Issue by gbonline** [ari/jobsworth#512]
Hi, i'm trying this application and I see some issues on Timeline index list: some icons don't show because some Missing Traduction errors for a wrong key name in rb files.
The first:
in views/timeline/index.html.erb, line37 there is a wrong   filter_status.wiki_addictions  ->  becomes  wiki_additions 
the second:
in views/activities/_log_row.html.erb, line 15, there is a wrong activities.Reverted -> becomes  activities.reverted   

Hope this help

**Comment by ari** [comment]
Can you please explain a bit more what you see is wrong or perhaps submit a pull request if you already can see the solution. What is a Traduction error?

**Comment by gbonline** [comment]
Hi, thanks for attention.
I'm sorry for mistake on "Traduction". I'm italian and i wrote on late night so i 'didn't translate correctly.
Traduction stay for Translation
I downloaded the master.zip and installed this app under ruby 2.1.5, added the demo datas, then in the firefox browser, after the first login with default admin, I choice in the left drop-down menu Timeline. In the Timeline list in the 2nd or 3rd column appear an icon: some icons don't show and appear an html code, and with CTRL-U to show the source html code, it's possible to see the entire message: 
    
    <span> ...  Missing Translation of "not find key" </span>

So looking for key in en.yml file and in the rb file I've found what i wrote: in 2 rb file ther'are wrong translation keys, that are:  
in views/timeline/index.html.erb, line37 there is a wrong t key:  

    filter_status.wiki_addictions -> must be wiki_additions, there is a unneeded "c" 

the second:
in views/activities/_log_row.html.erb, line 15, there is a wrong t key:   

    activities.Reverted -> must be activities.reverted , there is a 'R' uppercase instead lowercase

But I would like to add another little issue in the en.yml file.
the key en.boolean with two values yes and no that are written in plain text, I had to correct them as string to see them correctly like:
'yes': 'yes'
'no': 'no'
Take a look in the rb files and en.yml file
Hope this help
I don't think a fork is necessary for this small issues
Giorgio

**Comment by gbonline** [comment]
Hi, I've taken some screen picture to see what I mean
![screenshot from 2015-05-25 12 46 12](https://cloud.githubusercontent.com/assets/3273873/7796228/6d3a3a20-02dd-11e5-87a7-8b514f36f96f.png)
![screenshot from 2015-05-25 12 46 57](https://cloud.githubusercontent.com/assets/3273873/7796229/6d3e1a6e-02dd-11e5-9b38-f065183ad8ac.png)
![screenshot from 2015-05-25 12 47 53](https://cloud.githubusercontent.com/assets/3273873/7796230/6d471100-02dd-11e5-916a-99030169c934.png)
![screenshot from 2015-05-25 12 48 09](https://cloud.githubusercontent.com/assets/3273873/7796231/6d4d2054-02dd-11e5-9b8b-306b5ae01b76.png)
![screenshot from 2015-05-25 12 51 24](https://cloud.githubusercontent.com/assets/3273873/7796234/6dbaca96-02dd-11e5-96a4-0298b62cfee9.png)

**Comment by ari** [comment]
@nasa42 Could you please take a look at this. Looks like a simple bug to fix.

**Comment by nasa42** [comment]
These changes will be available in 4.0. Thanks @gbonline.
