### ISSUE TITLE
Problems to create war file from windows of this project

### ISSUE THREAD

**Issue by erotundo** [ari/jobsworth#513]
Hi.

I have a problem because i try to run the application with Tomcat, but i need to generate war file for this, i use warbler to do that but not work, throw error like this

NoMethodError: undefined method 'exist?' for Zip::File:Class.

I need to now the all version for create a war file please

**Comment by nasa42** [comment]
Make sure you are using "bundle exec warble war" to generate the .war file
so that correct version of the gem is loaded.
Also, if you are looking for an already packaged .war file, hang on, we'll
be publishing an official .war file for 4.0 release soon.


Cheers.
- Vikrant

**Comment by ari** [comment]
No response from user, so assuming this is sorted.
