### ISSUE TITLE
Final Release 4.0 is missing assets

### ISSUE THREAD

**Issue by mfranke** [ari/jobsworth#514]
The war-file is missing css, js, and gif-files in the assets-folder.
Installation on Win7 x64 and Tomcat 7.0 threw errors about one empty jar-file:
ROOT/WEB-INF/lib/gems-gems-warbler-1.4.7-spec-sample_war-some.jar

Logging in to the page worked but there are no images, no css and no javascript-functionality. Firefox reports 404 for the following files:

.../assets/application.js [HTTP/1.1 404 Not Found 136ms]
.../assets/application.css [HTTP/1.1 404 Not Found 233ms]
.../assets/spinner.gif [HTTP/1.1 404 Not Found 306ms]
.../assets/logo.gif [HTTP/1.1 404 Not Found 547ms]
.../assets/configure.png [HTTP/1.1 404 Not Found 212ms]
.../assets/delete.png [HTTP/1.1 404 Not Found 339ms]
.../assets/feed.png [HTTP/1.1 404 Not Found 437ms]
.../assets/spinner.gif [HTTP/1.1 404 Not Found 199ms]
.../assets/configure.png [HTTP/1.1 404 Not Found 196ms]

**Comment by nasa42** [comment]
We are aware of this issue, and working on a fix. Expect it to be released
soon.

**Comment by nasa42** [comment]
Fixed in 4.0.1.
