### ISSUE TITLE
4.0.1 war-file bug (invalid zip file)

### ISSUE THREAD

**Issue by agutl** [ari/jobsworth#516]
The ROOT.war contains the file 'WEB-INF/lib/gems-gems-warbler-1.4.7-spec-sample_war-some.jar' which is of zero size, however a valid empty zip file should be 22 bytes long.

This makes the deployment to tomcat on Ubuntu 12.04 fail as it struggles with the invalid jar file. I got it to work by simply removing the file from ROOT.war.

Deploying to the tomcat version included in Ubuntu 14.04 works without modifying the file though.

**Comment by agutl** [comment]
Just noticed this is the same file as in #514. Well the missing resources bug is gone :), just the zero length jar troublemaker remains.

**Comment by nasa42** [comment]
Upstream https://github.com/jruby/warbler/issues/256
