### ISSUE TITLE
Not able to deploy the war in Ubuntu 14.04

### ISSUE THREAD

**Issue by Ramakrishnan45** [ari/jobsworth#523]
Internal Server Error (500)
Request Method: 	GET
Request URL: 	http://127.0.0.1:8080/jobsworth/

undefined method `+' for nil:NilClass from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/config/initializers/010_devise.rb:6:in `(root)' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/devise-2.2.8/lib/devise.rb:267:in `setup' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/config/initializers/010_devise.rb:3:in `(root)' from org/jruby/RubyKernel.java:1091:in `load' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:1:in `(root)' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/engine.rb:593:in `Engine' from org/jruby/RubyBasicObject.java:1566:in `instance_exec' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/engine.rb:592:in `Engine' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `run_initializers' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/gems/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing' from org/jruby/RubyKernel.java:1072:in `require' from /var/lib/tomcat7/webapps/jobsworth/WEB-INF/config/environment.rb:5:in `(root)' from file:/var/lib/tomcat7/webapps/jobsworth/WEB-INF/lib/gems-gems-jruby-rack-1.1.18-lib-jruby-rack-1.1.18.jar!/jruby/rack/rails/environment3.rb:1:in `(root)' from file:/var/lib/tomcat7/webapps/jobsworth/WEB-INF/lib/gems-gems-jruby-rack-1.1.18-lib-jruby-rack-1.1.18.jar!/jruby/rack/rails/environment3.rb:25:in `load_environment'

**Comment by nasa42** [comment]
Can you check if `config/application.yml` exists?

**Comment by Ramakrishnan45** [comment]
Yes the application.yml exists in the location /var/lib/tomcat7/webapps/ROOT/WEB-INF/config

The previous issues was due to the context.xml is not configured. I have properly configred now. and this error is solved. 

Now I receive the following error, I already have the context.xml filled in /etc/tomcat7/context.xml
<b>Configuration:</b>
<code>
    <Resource name="jdbc/jobsworth"  removeAbandoned="true"
    auth="Container" type="javax.sql.DataSource"
    maxActive="100" maxIdle="30" maxWait="10000"
    username="root" password="password"
    driverClassName="com.mysql.jdbc.Driver" batchSize="-1"
    url="jdbc:mysql://127.0.0.1:3306/jobsworthdb?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf8"
    validationQuery="select 1"/> </code>

<b> ERROR:</b> initialization failed
org.jruby.rack.RackInitializationException: jdbc adapter requires :driver and :url (got :driver = mysql)
	from /var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.3.16/lib/arjdbc/jdbc/connection.rb:89:in `setup_jdbc_factory'


Can you help me with this issue?

**Comment by ari** [comment]
Are you using 4.1 beta 1?

**Comment by Ramakrishnan45** [comment]
No! I thought 4.0 is stable.
Do you have any Idea when you are planning to release 4.1? Or compilation of the recent code help?

Since the installation procedure is not so clear and more generic. It would help if you have a demo setup installation procedure of the initial steps. (Dependencies and configuration)

Just a thought: How is the step 3 and 4 different from 5 and 6. Why is it repeated again?

**Comment by ari** [comment]
Try 4.1b1 and see if the problem is solved. I just fixed the duplicate documentation steps, thanks for pointing that out!

**Comment by Ramakrishnan45** [comment]
Thanks!

I'll try and update you.
Just realized you already have some documentation in http://ari.github.io/jobsworth/

**Comment by Ramakrishnan45** [comment]
I've tried with 4.1b1 (recent release) but with the same error.
<b>ERROR:</b> jdbc adapter requires :driver and :url (got :driver = mysql)

<h5>context.xml</h5>
    <Context swallowOutput="true">
        <WatchedResource>WEB-INF/web.xml</WatchedResource>

        <Resource name="jdbc/jobsworth"
            removeAbandoned="true"
            auth="Container" type="javax.sql.DataSource"
            maxActive="100" maxIdle="30" maxWait="10000"
            username="root" password="password"
            driverClassName="com.mysql.jdbc.Driver" batchSize="-1"
            url="jdbc:mysql://127.0.0.1:3306/jobsworthdb?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf8"
            validationQuery="select 1"/>

    <some more configurations....>

    </Context>

<h5>database.yml</h5>
    production:
        adapter: jdbc
        driver: mysql
        jndi: java:comp/env/jdbc/jobsworth
        encoding: utf8
        pool: 100

-> I suspect `jndi` configuration is not working. (ie. not fetching from context.xml)

<h5>Error from catalina.out (/var/log/tomcat7) </h5>
Oct 07, 2015 12:18:02 PM org.apache.catalina.core.NamingContextListener addResource
WARNING: Failed to register in JMX: javax.naming.NamingException: com.mysql.jdbc.Driver
Oct 07, 2015 12:18:02 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ROOT.war

-> Is there any dependency package that I should have installed?

FYI: I have tried installing libmysql-java. That doesn't work.
I have installed default-jre (java version 7)

**Comment by ari** [comment]
@Ramakrishnan45 Did you ever get this sorted?

**Comment by robert-scheck** [comment]
As per #641 the trick to get rid of the 

> jdbc adapter requires :driver and :url (got :driver = mysql)

error message is likely to add

```
factory="org.apache.commons.dbcp.BasicDataSourceFactory"
```

within the `<Resource>` tag, because you are likely missing `org.apache.tomcat.dbcp.dbcp.BasicDataSourceFactory` (which would be the alternative, then you wouldn't have to add another `factory` option.
