### ISSUE TITLE
Upgrade Rails to 4.2

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#528]
https://travis-ci.org/ari/jobsworth/jobs/101369585

We have a few issues, mainly caused by our upgrade of the devise gem I think. Vikrant, can you or your team sort this out please.

**Comment by zaidakram** [comment]
Fixed in cfe8d53d9031a08b23e133a964c18fc9026e4713

**Comment by nasa42** [comment]
:+1:

**Comment by nasa42** [comment]
Been just reviewing rails4 branch code, since we already use strong_parameters, we shouldn't use protected_attributes any more?

**Comment by zaidakram** [comment]
Yeah, protected_attributes was extracted out of rails core in Rails 4. No need to white-list/blacklist attributes on model level when you are doing at the controller level. Strong Parameters give you more control per end-point, while you have same white-list/blacklist for every end-point with protected_attributes.
