### ISSUE TITLE
Travis random failures

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#552]
https://travis-ci.org/ari/jobsworth/builds

There doesn't seem to be a pattern and I'm not convinced any particular commit it causing the issues. Perhaps we have a race condition somewhere?

**Comment by ari** [comment]
@k41n Have you any clues as to what is causing this behaviour?

**Comment by k41n** [comment]
Usually it is connected either to database not cleared or stubs not removed. I see that database is being cleared by DatabaseCleaner, so first reason is not the one. Looks like that needs investigation

**Comment by ari** [comment]
Looks like this is resolved.
