### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by PBoomkamp** [ari/jobsworth#553]
Hello i have installed Tomcat and mysql and folowed all the instructions after deploy i get a error i can't solve.

Internal Server Error (500)
Request Method:	GET
Request URL:	http://192.168.2.16:8080/root/
-----
undefined method `+' for nil:NilClass from /var/lib/tomcat7/webapps/root/WEB-INF/config/initializers/010_devise.rb:6:in `(root)' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/devise-2.2.8/lib/devise.rb:267:in `setup' from /var/lib/tomcat7/webapps/root/WEB-INF/config/initializers/010_devise.rb:3:in `(root)' from org/jruby/RubyKernel.java:1059:in `load' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:1:in `(root)' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `load' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:245:in `load' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/engine.rb:593:in `Engine' from org/jruby/RubyBasicObject.java:1623:in `instance_exec' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/engine.rb:592:in `Engine' from org/jruby/RubyArray.java:1613:in `each' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `run_initializers' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!' from /var/lib/tomcat7/webapps/root/WEB-INF/gems/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing' from org/jruby/RubyKernel.java:1040:in `require' from /var/lib/tomcat7/webapps/root/WEB-INF/config/environment.rb:5:in `(root)' from file:/var/lib/tomcat7/webapps/root/WEB-INF/lib/gems-gems-jruby-rack-1.1.19-lib-jruby-rack-1.1.19.jar!/jruby/rack/rails/environment3.rb:1:in `(root)' from file:/var/lib/tomcat7/webapps/root/WEB-INF/lib/gems-gems-jruby-rack-1.1.19-lib-jruby-rack-1.1.19.jar!/jruby/rack/rails/environment3.rb:25:in `load_environment'

Can someone help me

**Comment by ari** [comment]
Which version are you using? Did you configure context.xml?

Typically you would not go to /root/ as a path.

**Comment by ari** [comment]
I'm going to close this task with no response for two weeks. I assume you've sorted your problem. At any rate, I recommend you:

1. Use the mailing list for assistance
2. Try a build from master. Deployment should be smoother now.
