### ISSUE TITLE
InvalidTimezoneIdentifier

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#574]
Not sure what action in the UI caused this.

```
Apr 27, 2016 12:32:34 PM org.apache.catalina.core.StandardWrapperValve invoke
INFO: Apr 27, 2016 12:32:34 PM org.apache.catalina.core.ApplicationContext log
INFO:
TZInfo::InvalidTimezoneIdentifier (Invalid identifier):
  app/models/user.rb:274:in `tz'
  app/models/user.rb:343:in `schedule_tasks'
  app/controllers/tasks_controller.rb:21:in `block in index'
  app/controllers/tasks_controller.rb:18:in `block in index'
  app/controllers/tasks_controller.rb:17:in `index'
```

**Comment by k41n** [comment]
@ari  This issue is invoked by error in user's timezone. I'd like to suggest to add validation for user's timezone to avoid similar issues in future.  We can find and fix this mistake in database or just use UTC if user's timezone is invalid. What do you think?

**Comment by ari** [comment]
Seems reasonable to use UTC if it isn't valid. Or I'd be happy to have a once off migration to fix/reset all timezones that aren't correct and then ensure validation keeps it correct in the future.

**Comment by ari** [comment]
This wasn't fixed properly. I'm still seeing:

```
TZInfo::InvalidTimezoneIdentifier (Invalid identifier):
  app/models/user.rb:278:in `tz'
  app/models/user.rb:347:in `schedule_tasks'
  app/controllers/tasks_controller.rb:23:in `block in index'
  app/controllers/tasks_controller.rb:20:in `block in index'
  app/controllers/tasks_controller.rb:19:in `index'
```

when viewing the task list with an offending task.

Looking at this commit, it isn't right. We don't want a rake task, instead we want a migration to fix all broken data.

**Comment by ari** [comment]
Confirmed now fixed.
