### ISSUE TITLE
new_records/new_record

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#575]
Emails coming into the system were failing. The only error was:

```
Apr 27, 2016 12:31:42 PM org.apache.catalina.core.StandardWrapperValve invoke
INFO: Apr 27, 2016 12:31:42 PM org.apache.catalina.core.ApplicationContext log
INFO:   Couldn't find template for digesting: new_records/new_record
```

**Comment by k41n** [comment]
@ari How can I reproduce this error?

**Comment by ari** [comment]
@k41n Use the script here https://github.com/ari/jobsworth/blob/master/script/receive which is designed to accept email from external sources. A new task should be created with appropriate users. We really need some tests around this if possible.

**Comment by ari** [comment]
Did you ever get to the bottom of what template for digesting it is complaining about?

**Comment by ari** [comment]
I've renamed this task because it looks like it wasn't about email.

**Comment by ari** [comment]
This error is still happening, but I'm not sure what causes it.

**Comment by k41n** [comment]
It's look like rails issue. https://github.com/rails/rails/issues/15255.

**Comment by ari** [comment]
Closing since it isn't causing a problem.
