### ISSUE TITLE
task_num is null

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#615]
A user is trying to log in and immediately gets the following error. The error is the same no matter if they clear their cookies or use a different browser.

```
Jun 13, 2016 5:01:23 PM org.apache.catalina.core.ApplicationContext log
INFO:
ActionView::Template::Error (No route matches {:action=>"edit", :controller=>"tasks", :id=>nil} missing required keys: [:id]):
     5: <div class="<%= user.top_next_task == task ? 'top-next-task' : nil %>">
     6:   <%= human_future_date(pill_date, user.tz) %>
     7:   <span class="<%= task.css_classes %>">
     8:     <%= link_to "<b>##{task.task_num}</b>".html_safe, task_view_path(task.task_num), 'data-taskid' => task.id, "data-content" => task_detail(task, user) %>
     9:     <%= task.name %>
    10:
    11:     <% case time %>
  app/views/tasks/_task_line.html.erb:8:in `_app_views_tasks__task_line_html_erb__68180863_41158'
  app/views/tasks/_nextTasks.html.erb:11:in `block in _app_views_tasks__next_asks_html_erb__414461730_40710'
  app/models/user.rb:364:in `block in schedule_tasks'
  app/models/user.rb:352:in `schedule_tasks'
  app/views/tasks/_nextTasks.html.erb:9:in `_app_views_tasks__next_asks_html_erb__414461730_40710'
  app/views/layouts/application.html.erb:10:in `block in _app_views_layouts_application_html_erb___1004114448_28498'
  app/views/layouts/application.html.erb:1:in `_app_views_layouts_application_html_erb___1004114448_28498'
```

**Comment by ari** [comment]
So, I fixed the symptom. A task had been created with task_num = nil. Not sure how, but I'd sure like to fix that and even make task_num not null in the db. I think we previously had trouble with this because of the way Rails works, but not sure if Rails 4 makes that easier to get around.

**Comment by ari** [comment]
@k41n What would be required to make the task_num NOT NULL?

**Comment by k41n** [comment]
@ari We can forbid record of null value to database. Just change column and add :null => false via migration. And set value for existing records with task_num=null

**Comment by ari** [comment]
@k41n You are trying to explain to me how NOT NULL works in a database?

How shall I put this without coming across as an arrogant twat? Let's just say that it would be more productive in our conversations if you assumed that I've been working with databases for over 20 years and am heavily involved in the creation of an [ORM](http://cayenne.apache.org). So my shorthand statement of "what would be required" wasn't "please explain not null". Rather I want you to look at:

* does any code persist null task_num to the db, for example to save a temporary copy of the task before updating the task_num using an sql MAX().
* do task templates require task_num is null
* do any other code paths prevent us from changing this in the db?

**Comment by k41n** [comment]
Task templates doesn't require task_num with value nil. There are two callbacks in AbstractTask model. First one is set task_num = nil before create. Another one is trying to select and set task_num value for task in transaction after create. And if transaction will be rolled back for any reason task will be saved with task_num = nil
Probably it happened.
