### ISSUE TITLE
Cannot edit task properties

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#617]
/properties/23/edit

```
Jun 14, 2016 5:55:18 PM org.apache.catalina.core.ApplicationContext log
INFO:
ActionView::Template::Error (No such file or directory - /var/squish/app/squish1/webapps/ROOT/WEB-INF/app/assets/images/icons):
    34:         <div class="control-group">
    35:           <label><%= t "properties.icon_url" %></label>
    36:           <div class="controls">
    37:             <%= f.select :icon_url, task_icon_options(pv), {}, { :index => pv.id } %>
    38:           </div>
    39:         </div>
    40:
  app/helpers/application_helper.rb:166:in `task_icon_options'
  app/views/properties/_property_value.html.erb:37:in `block in _app_views_properties__property_value_html_erb___1265235210_8881794'
  app/views/properties/_property_value.html.erb:9:in `_app_views_properties__property_value_html_erb___1265235210_8881794'
  app/views/properties/_form.html.erb:37:in `block in _app_views_properties__form_html_erb___832113342_8881484'
  app/views/properties/_form.html.erb:36:in `block in _app_views_properties__form_html_erb___832113342_8881484'
  app/views/properties/_form.html.erb:1:in `_app_views_properties__form_html_erb___832113342_8881484'
  app/views/properties/edit.html.erb:7:in `_app_views_properties_edit_html_erb__315777144_8881300'
```

**Comment by ari** [comment]
Thanks, that fixed the initial bug. But there are still problems with being able to create and edit properties.

1. Cannot tick the 'default' checkbox. 
2. Clicking save without adding a new property causes a new blank property to be added
3. "Remove value" in new property section make no sense
4. Drag and drop to rearrange ordering doesn't work

I'd be happy with a completely different UI if that made it easier to implement fixes to the above. This is a part of the system that is rarely changed, so it needs to be simple and intuitive. Instead of choosing an icon by name, we should be choosing it by icon... Likewise, a colour picker should be trivial to add here and we probably already have one in the js libraries we use.

Is this page easier to rebuild from scratch rather than fix?

In addition, where do we currently use the icon and colour options? I suspect almost nowhere, but they could be useful to bring back. I particularly like the idea of colouring tasks, but how do we deal with multiple colours? Trello does it with little coloured bars which is an interesting idea.

**Comment by k41n** [comment]
I think first we need to fix current errors. After that we can change UI if it would be needed. @ari

**Comment by ari** [comment]
OK, if that's easiest. Just want to let you know that if the code is a mess, don't hesitate to rebuild it.

**Comment by k41n** [comment]
@ari I can add image picker for last part of issue, but it would be easier with upgraded select2 which should be done in PR https://github.com/ari/jobsworth/pull/631

**Comment by k41n** [comment]
@ari Initial task is done. Can we close this issue and move changes in UI in new one?

**Comment by ari** [comment]
Yes, good.
