### ISSUE TITLE
Remove Check Box From To do list

### ISSUE THREAD

**Issue by meganish** [ari/jobsworth#621]
![screen shot 2016-06-17 at 12 11 52 pm](https://cloud.githubusercontent.com/assets/19790509/16138818/bbd3931e-3484-11e6-9a5c-8b545b621b6d.png)
When creating a new task, the checkbox option is not needed.

Checkboxes should only appear next to existing list items.

**Comment by ari** [comment]
This is a regression after the Rails upgrade.

**Comment by ari** [comment]
@k41n This problem is not solved.

**Comment by ari** [comment]
OK, my bad. It is solved.

**Comment by ari** [comment]
I found 245 blank todo items in our database and deleted them.
