### ISSUE TITLE
Target date better UI

### ISSUE THREAD

**Issue by meganish** [ari/jobsworth#622]
![screen shot 2016-06-17 at 1 01 17 pm](https://cloud.githubusercontent.com/assets/19790509/16139568/30591360-348c-11e6-9fc6-7312af6d4106.png)

* Change label 'Target Date' to 'Target'
* Add snooze button and dropdown list

```
<button class="btn btn-mini" type="button">snooze
  <span class="caret"></span>
</button>
```
Dropdown list should have options:

* tomorrow
* next week
* until customer reply
* until other task...
* until date...

Once a choice is made the button changes to

`<button class="btn btn-mini btn-primary" type="button"> snoozed </button>`

pressing it again reverts it to the original state and clears any snooze option.

The label changes to "Snoozed until".

If 'until date...' was chosen, then the target date is retained as the new snooze date (and can then be edited). If "next week" is chosen, then the coming Monday is populated in the date field. In all cases, the date or task number can be edited, except if you choose "customer reply".

![screen shot 2016-06-17 at 1 12 19 pm](https://cloud.githubusercontent.com/assets/19790509/16139716/a5c8133e-348d-11e6-8545-10912f992b22.png)

**Comment by ari** [comment]
@k41n There isn't really any new functionality here, just cleaner simpler UI.

We can also remove the whole "Snooze" section from lower down in the left sidebar

**Comment by meganish** [comment]
Note, we switched Estimate and Snoozed Until. Please ensure they are shown right way around in the update

Also, remove green forecast date from display
