### ISSUE TITLE
Forecast Date in List View

### ISSUE THREAD

**Issue by meganish** [ari/jobsworth#623]
In the list view, the 'forecast date' doesn't correlate to anything reasonable. 

Please ensure this date is consistent with actual forecast dates chosen.

Where a task is snoozed, forecast date should be 'snoozed'

**Comment by ari** [comment]
I just deployed this patch and it made the display much worse. Now we just see "NaN years ago" everywhere.

**Comment by ari** [comment]
This problem seems to have been resolved by deleting caches or maybe by other commits in the meantime.
