### ISSUE TITLE
Updating snooze date did not update assigned users forecast

### ISSUE THREAD

**Issue by meganish** [ari/jobsworth#624]
I updated the snooze date on a task to 1/2/2017 however, the forecast still shows as being actioned today

![screen shot 2016-06-17 at 12 22 03 pm](https://cloud.githubusercontent.com/assets/19790509/16140036/9743ce4a-3490-11e6-8bc6-ea1dba34d391.png)

**Comment by ari** [comment]
Closed with no commit, or is this fixed in another task?
