### ISSUE TITLE
Unable to add snippets to tasks 

### ISSUE THREAD

**Issue by meganish** [ari/jobsworth#625]
Using the menu in the below screenshot, I am able to select a snippet
![menu](https://cloud.githubusercontent.com/assets/19790509/16221318/79f5c530-37d5-11e6-8734-50a903372a2a.png)

This however, creates an eternal pinwheel.

Expected: Snippet text loaded on comment field.

**Comment by ari** [comment]
Possibly related log:

`ActionController::RoutingError (No route matches [GET] "/images/indicator.gif"):`
