### ISSUE TITLE
Upgrade select2

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#626]
We are using select2 version 3.2 and need to upgrade to 4.0 in order to access some new functionality.

A quick search for "<%= select(" or "<select " in our code base reveals 37 matches. Each of those needs to be verified to see the upgrade didn't break anything.

**Comment by ari** [comment]
I'd like to look at adding this to our js:

`jQuery("select").select2( { minimumResultsForSearch: Infinity } );`

Perhaps that's too invasive on *every* select, but let's look to see how it might work for us. Maybe we need to explicitly add a "select2" class to each select element?

**Comment by ari** [comment]
@k41n Is this all done?

**Comment by k41n** [comment]
@ari Yes. It should be done. 
https://github.com/ari/jobsworth/pull/631
