### ISSUE TITLE
forecast date not updating

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#627]
1. Create a task and assign it to userA.
2. At this point the forecast date (as seen in the label next to the assigned user) is "20 days"
3. Assign the task to a different user

What happens:
* The forecast date does not change. It is still 20 days.
* After saving the task and reloading it, the forecast date is still wrong.
* Look in /users/99999/workplan for that user and see that the forecast date for that same task is correct and not 20 days.

What should happen:
* Ideally, the forecast date should be updated in real time even before you save the task. We'd need some sort of ajax call when you reassign the task in order to fetch an estimate (if it is wasn't 100% correct since we aren't going to re-order everything in real time)
* If this is too hard, then we should display no forecast date at all until after we save/reload the task and show the proper forecast.

**Comment by ari** [comment]
@k41n This looks like it might be fixed now at least when you reload the whole page. Should we leave the ajax realtime update until after we review the 'stage' ideas ?

**Comment by k41n** [comment]
@ari I think it makes sense. Forecast date could have value for each stage of task.
