### ISSUE TITLE
Test failure after email template upgrade

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#632]
@k41n Sorry to do this to you. I just committed some improvements to the outbound email templates, but this caused test failures. Could you please take a look and see whether the test just needs adjusting or if I actually broke the emails.

https://travis-ci.org/ari/jobsworth/jobs/140697171#L1874

**Comment by k41n** [comment]
Tests were fixed.

**Comment by ari** [comment]
Sorry, it would appear I broke it again. Either my git skills are a bit rubbish, or the conflict merge git resolved automatically for me is broken.
