### ISSUE TITLE
German language doesn't work in jobsworth 5.0M3

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#643]
After a fresh installation of jobsworth 5.0M3, I tried to switch the language of the webbased user interface to German using `http://…/users/1/edit` (via the drop-down menu in the right upper corner), by selecting "de" as `Language` and clicking the `Save` button. However, the effective language is still English, also after logout and login (the setting indeed says "de").

**Comment by ari** [comment]
The German translation was not bundled in the app, but I'll do that now and release another milestone. It is also incomplete, so you might like to work on the missing translations:

https://github.com/ari/jobsworth/tree/master/config/locales

This tool is quite useful for working on the translations: https://www.localeapp.com/projects/4135/translations?in_locale=14045&state=incomplete

Thanks

**Comment by ari** [comment]
I've released a beta now with German (what has been done) bundled in. We appreciate any assistance you can put into making translations better.

**Comment by robert-scheck** [comment]
Confirmed with 5.0 beta 1 as solved, thank you very much. Contributing to the translations might get a topic if the rest works as expected ;-)
