### ISSUE TITLE
Sort 'update milestone' list

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#645]
1. Go to task list
2. Choose cogwheel from filters
3. Save current filter
4. Update existing filter

List of milestones is not sorted. They should be alphabetical.

**Comment by ari** [comment]
Nope, this isn't the bug. The problem is that in the "update existing filter dialog" the list of milestones should be sorted alphabetically. Not the list of tasks. The list of milestones. Inside the dialog.

**Comment by k41n** [comment]
List of milestones is  sorted be alphabetical. It was wrong commit message.
