### ISSUE TITLE
Some email not accepted

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#647]
NoMethodError (undefined method `default' for #<Array:0x692bf8bb>):
  app/models/mailman.rb:27:in `initialize'
  app/models/mailman.rb:105:in `receive'
  app/models/mailman.rb:13:in `receive'
  app/controllers/emails_controller.rb:15:in `create'

**Comment by k41n** [comment]
Can't reproduce this issue. I need example of email which induce this exception.
