### ISSUE TITLE
Update milestone status

### ISSUE THREAD

**Issue by ari** [ari/jobsworth#649]
Milestones are not updating their status each night. They should progress from 'planning' to 'in progress' as the relevant dates are hit.

**Comment by k41n** [comment]
@ari I couldn't find any problems locally. Can we be sure that scheduler is enabled? Environment variable with name "JOBSWORTH_DISABLE_SCHEDULER" should not be defined.

**Comment by ari** [comment]
That's definitely not defined. Can we add some logging to the app when it runs the nightly schedule so we can see that it runs.

**Comment by k41n** [comment]
ok. I'll do that.

**Comment by k41n** [comment]
@ari I added logs with tag "SCHEDULER TEST". Now we should see how many milestones are waiting update, and how many milestones won't be updated by any reason.
