### ISSUE TITLE
Initialize default admin properly

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#656]
After a fresh installation of jobsworth 5.0 beta 1, I tried to switch the user language after the first login at `/users/1` from `en` to `de` (to test #643) and tried to save it, this however leads immediately to the error:

> Customer name can't be blank

Filling the field `Company` with `Default Company` solved this. Interestingly the error message talks about "customer", while the field is named "company". Honestly, I would anyway expect from the user perspective that the preloaded default data fills this field already.

**Comment by ari** [comment]
@k41n Andrei, this should be easy to fix. When a new tenant is created in the system we already create a user and company (customer), but it looks like they aren't linked to each other.
