### ISSUE TITLE
Ruby related warning regarding '&' at paperclip-4.3.6/lib/paperclip/storage/filesystem.rb:49

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#657]
The following ruby related warning is thrown with also in jobsworth 5.0 beta 1 after a fresh installation:

> INFO: Deploying web application archive /var/lib/tomcat/webapps/ROOT.war
> /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/paperclip-4.3.6/lib/paperclip/storage/filesystem.rb:49: warning: `&' after local variable or literal is interpreted as binary operator
> /usr/share/tomcat/webapps/ROOT/WEB-INF/gems/gems/paperclip-4.3.6/lib/paperclip/storage/filesystem.rb:49: warning: even though it seems like argument prefix

Yes, it's just a warning but it might be worth a fix through.

**Comment by ari** [comment]
Yes, we've seen it but can't fix the problem until paperclip fix it at their end. So nothing for us to do here.
