### ISSUE TITLE
Message "Invalid user or password" before login and after logout

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#658]
After a fresh installation of jobsworth 5.0 beta 1, I experience this:

Loading `http://localhost:8080` in the browser redirects to `http://localhost:8080/auth/users/sign_in`, which is fine so far. However at the same time, the error message 

> Invalid user or password

is shown. But loading `http://localhost:8080/auth/users/sign_in` directly does not lead to the message. The same occurs also after clicking "Logout", thus I assume this is related to HTTP redirects.

While this is indeed quite minor, it is still confusing from the user perspective to receive an error message before login and after logout.

**Comment by ari** [comment]
It funny that this has been happening for years and my brain just tunes it out. Let's fix this!
