### ISSUE TITLE
Date formats lack ISO 8601 and DIN ISO 8601:2006-09

### ISSUE THREAD

**Issue by robert-scheck** [ari/jobsworth#660]
After a fresh installation of jobsworth 5.0 beta 1, when visiting `/users/1/edit`, the following date formats are supported and available:

> 1/21/2007
> 21/1/2007
> 2007/1/21

First of all, I'm missing the very common ISO 8601 here, which would be `YYYY-MM-DD`:

> 2007-01-21

While above surely covers mainly English-speaking countries and regions properly, this is not suitable for e.g. Germany, Austria and Switzerland. Here DIN ISO 8601:2006-09 is common, thus:

> 21.01.2007
> 21.1.2007

Above is `DD.MM.YYYY` and `D.M.YYYY` technically spoken. Can you please add the three missing formats? Thank you.

**Comment by ari** [comment]
I'm confused about this request. We are only talking about human readable date formats here, so whether we use dashes, dots or slashes is irrelevant isn't it? At any rate, mostly in the app we use none of these and I might get rid of them entirely.

I'm tending to use "21 Jan 2007" as a format which is unambiguous and easier to read.

**Comment by robert-scheck** [comment]
Yes, we're talking about human readable date formats only – but that's why dashes, dots or slashes are important, because it's what people are used to read. Reading a date format that you are used to makes things faster.

Well, something like "21 Jan 2007" is even better, but needs to be taken care of at translation level.

**Comment by ari** [comment]
Moving to "21 Jan 2007" so closing this.
