### ISSUE TITLE
Can anyone tell me what version is running on www.clockingit.com?

### ISSUE THREAD

**Issue by roughneck** [ari/jobsworth#676]
Hey,

I've been trying to get my data from www.clockingit.com on my own server for weeks. Sent many emails to all email addresses I know, asked in forums etc. but no success so this is kind of my last resort.

On clockingit.com it says it's running on `v0.99.3`, so I checked that version out and got it running locally but when I try to import my SQL locally I get: `Column count doesn't match value count at row 1` for users, companies and many more. I've also tried `0.99.2`, `0.99.3.1` and `1.2` but I keep getting the same error message.

So does anyone know which version/commit I need to checkout in order to sucessfully import the database dump from clockingit.com?

Any help would be highly appreciated!

**Comment by frank-orellana** [comment]
That version is the one running accorging to the documentation

You can find more help in this forum:

https://groups.google.com/forum/#!forum/jobsworth

But be warned it is looking like an abandoned project and many people are having old issues. I made some scripts to install and migrate data from hosted to the latest version of jobsworth (clockingit last version was 0.99.3 so maybe you should migrate too).

You can find these scripts here: https://github.com/frank-orellana/jobsworth-installer 

I made them so it can install everything needed to run jobsworth in a server (tomcat, mariadb, java, etc) And there is also a script to migrate the data from the hosted version to your local install in there.

Maybe you should try all that in a virtual machine in case you run into problems!

**Comment by roughneck** [comment]
Thanks a lot, that's just what I was looking for! I'll give it a try.

**Comment by frank-orellana** [comment]
Great, let us know if everything works ok for you

**Comment by roughneck** [comment]
First attempt wasn't successful, I keep getting: `ERROR 1698 (28000): Access denied for user 'root'@'localhost'` when trying to migrate the script; even when I copy + paste the password. Reinstalled vagrant machine twice, tried to reset root password many times, no luck.

Will try again another day.

**Comment by frank-orellana** [comment]
Possibly it is the root user of the mysql database, please check if it copied the data anyway (and maybe you should open this issue in the installer project just in case)

**Comment by roughneck** [comment]
Turned out to that packages generated by Ubuntu by default have unix_socket authentication for root. I changed it to password login and now it works 👍
